---
distFolder: _site
setup:
- name: Set up Ruby 2.7
  action: ruby/setup-ruby@v1
  properties:
    ruby-version: 2.7
    bundler-cache: true
build:
  name: Build Jekyll
  command: bundle exec jekyll build
